<?php

namespace Subscriber\Modules\Session\Controllers;

use Subscriber\Common\Mvc\Controller;

class ControllerBase extends Controller
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->view->setLayout('dashboard_login');
        $this->view->stylesheets = [
            "/AdminLTE-2.4.10/plugins/iCheck/square/blue.css"
        ];
        $this->view->cssClass = "login-page";
        $this->view->scripts = [
            "/AdminLTE-2.4.10/bower_components/jquery/dist/jquery.min.js",
            "/AdminLTE-2.4.10/bower_components/fastclick/lib/fastclick.js",
            "/AdminLTE-2.4.10/dist/js/adminlte.min.js",
            "/AdminLTE-2.4.10/plugins/iCheck/icheck.min.js",
        ];
    }
}
