<?php


namespace Daudau\Modules\Admin\Controllers;


use Daudau\Common\Models\Bookmark\Category;
use Daudau\Common\Models\Recipe\RawMaterial;
use Daudau\Common\Models\Users\Role;
use Daudau\Common\Models\Users\Status;
use Daudau\Modules\Admin\Forms\categoryForm;
use Daudau\Modules\Admin\Forms\RawMaterialForm;
use Daudau\Modules\Admin\Forms\RoleForm;
use Phalcon\Tag;

class categoryController extends BaseDashboardController
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function listcategoryAction()
    {
        $this->view->activemenu = [
            'bookmark',
            'category_list'
        ];
        $this->view->names = [
            [
                'label' => 'Danh sách nhóm công thức',
                'href' => '/admin/category/listCategory'
            ],
        ];
        $current_page = $this->request->getQuery('page', 'int', 1);
        $limit_of_page = 10;
        $form = new categoryForm();
        $form->search();
        $this->view->form = $form;
        $cond_array = [];
        $param_url = $this->request->getQuery();
        $bind_data = [];
        foreach ($param_url as $key => $value) {
            Tag::setDefault($key, $value);
            if ($key != '_url' && $key != 'page' && $value != '') {
                if ($key == 'active' && $value != '') {
                    $value = trim($value);
                    array_push($cond_array, "$key =:$key:");
                    $bind_data[$key] = $value;
                } else if ($key == 'active' && $value == '') {
                    array_push($cond_array, "active='1'");
                } else {
                    $value = trim($value);
                    array_push($cond_array, "$key =:$key:");
                    $bind_data[$key] = $value;
                }
            }
        }

        $conditions = implode(' AND ', $cond_array);
        $category = Category::find([
            'conditions' => $conditions,
            'bind' => $bind_data,
            'limit' => $limit_of_page,
            'offset' => (($current_page - 1) * $limit_of_page),
        ]);
        $category_total_record = Category::count([
            'conditions' => $conditions,
            'bind' => $bind_data
        ]);
        if (count($category) == 0) {
            $this->view->category = null;
        } else {
            $this->view->category = $category;
        }
        $this->view->paging = $this->helper->util()->paging($category_total_record, $this->request->getQuery(), $limit_of_page, $current_page);

    }

    public function createcategoryAction()
    {
        $this->view->activemenu = [
            'bookmark',
            'category_create'
        ];
        $this->view->names = [
            [
                'label' => 'Tạo nhóm công thức',
                'href' => '/admin/category/createCategory'
            ],
        ];
        $category = new Category();
        $form = new categoryForm();
        $form->create();
        $this->view->form = $form;
        if ($this->request->isPost()) {
            $post = $this->request->getPost();
            $category->setId($category->getSequenceId());
            $form->bind($post, $category);

            $error = Category::checkValidations($post);
            if (count($error) != 0) {
                foreach ($error as $er) {
                    $this->flashSession->error($this->helper->translate($er));
                }
            } else {
                if ($category->save()) {
                    $this->flashSession->success($this->helper->translate('Tạo nhóm công thức mới thành công'));
                    return $this->redirect('/admin/category/listcategory');
                } else {
                    foreach ($category->getMessages() as $message) {
                        $this->flashSession->error($this->helper->translate($message->getMessage()));
                    }
                    $form->setEntity($post);
                }
            }
        }
    }

    public function deletecategoryAction($id)
    {
        $this->view->disable();
        $status_id_disable = Status::getStatusIdByCode('disable');
        $category = Category::findFirst([
            'conditions' => 'id=:id:',
            'bind' => [
                'id' => $id
            ]
        ]);
        if ($category) {
            $category->setStatusId($status_id_disable);
            $this->flashSession->success($this->helper->translate('Xóa thành công'));
            $category->save();
        } else {
            $this->flashSession->warning($this->helper->translate('Không tìm thấy nhóm công thức'));
        }
        return $this->redirect('/admin/category/listCategory');
    }

    public function editcategoryAction($id)
    {
        $this->view->activemenu = [
            'bookmark',
            'category_list'
        ];
        $this->view->names = [
            [
                'label' => 'Chỉnh sửa nhóm công thức',
                'href' => '/admin/category/listCategory'
            ],
        ];
        $form = new categoryForm();
        $form->edit();

        $category = Category::findFirst([
            'conditions' => 'id=:id:',
            'bind' => [
                'id' => $id
            ]
        ]);
        if ($this->request->isPost()) {
            $post = $this->request->getPost();
            if($post['name'] != $category->getName())
            {
                $check=Category::findFirst([
                    'conditions'=>'name=:name:',
                    'bind'=>[
                        'name'=>$post['name']
                    ]
                ]);
                if($check)
                {
                    $this->flashSession->error('Tên nhóm công thức đã tồn tại');
                    return $this->redirect('/admin/category/listCategory');
                }
            }
            if($post['code'] != $category->getCode())
            {
                $check=Category::findFirst([
                    'conditions'=>'code=:code:',
                    'bind'=>[
                        'code'=>$post['code']
                    ]
                ]);
                if($check)
                {
                    $this->flashSession->error('Mã số nhóm công thức đã tồn tại');
                    return $this->redirect('/admin/category/listCategory');
                }
            }
            $form->bind($post, $category);
            if ($category->save()) {
                $this->flashSession->success($this->helper->translate('Chỉnh sửa nhóm công thức thành công'));
                return $this->redirect('/admin/category/listCategory');
            } else {
                foreach ($category->getMessages() as $message) {
                    $this->flashSession->error($this->helper->tranlate($message->getMessage()));
                }
            }
        } else {
            $form->setEntity($category);
        }

        $this->view->form = $form;
    }

    public function viewcategoryAction($id)
    {
        $this->view->activemenu = [
            'bookmark',
            'category_list'
        ];
        $this->view->names = [
            [
                'label' => 'Xem thông tin nhóm công thức',
                'href' => '/admin/category/listCategory'
            ],
        ];
        $form = new categoryForm();
        $form->view();
        $category = Category::findFirst([
            'conditions' => 'id=:id:',
            'bind' => [
                'id' => $id
            ]
        ]);
        $form->setEntity($category);
        $this->view->form = $form;
    }
}