<?php


namespace Daudau\Modules\Admin\Controllers;


use Daudau\Common\Models\Recipe\Quantitative;
use Daudau\Common\Models\Recipe\RawMaterial;
use Daudau\Common\Models\Users\Role;
use Daudau\Common\Models\Users\Status;
use Daudau\Modules\Admin\Forms\QuantitativeForm;
use Daudau\Modules\Admin\Forms\RawMaterialForm;
use Daudau\Modules\Admin\Forms\RoleForm;
use Phalcon\Tag;

class QuantitativeController extends BaseDashboardController
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function listQuantitativeAction()
    {
        $this->view->activemenu = [
            'recipe',
            'quantitative_list'
        ];
        $this->view->names = [
            [
                'label' => 'Danh sách định lượng',
                'href' => '/admin/quantitative/listQuantitative'
            ],
        ];
        $current_page = $this->request->getQuery('page', 'int', 1);
        $limit_of_page = 10;
        $form = new QuantitativeForm();
        $form->search();
        $this->view->form = $form;
        $cond_array = [];
        $param_url = $this->request->getQuery();
        $bind_data = [];
        foreach ($param_url as $key => $value) {
            Tag::setDefault($key, $value);
            if ($key != '_url' && $key != 'page' && $value != '') {
                if ($key == 'active' && $value != '') {
                    $value = trim($value);
                    array_push($cond_array, "$key =:$key:");
                    $bind_data[$key] = $value;
                } else if ($key == 'active' && $value == '') {
                    array_push($cond_array, "active='1'");
                } else {
                    $value = trim($value);
                    array_push($cond_array, "$key =:$key:");
                    $bind_data[$key] = $value;
                }
            }
        }

        $conditions = implode(' AND ', $cond_array);
        $quantitative = Quantitative::find([
            'conditions' => $conditions,
            'bind' => $bind_data,
            'limit' => $limit_of_page,
            'offset' => (($current_page - 1) * $limit_of_page),
        ]);
        $quantitative_total_record = Quantitative::count([
            'conditions' => $conditions,
            'bind' => $bind_data
        ]);
        if (count($quantitative) == 0) {
            $this->view->quantitative = null;
        } else {
            $this->view->quantitative = $quantitative;
        }
        $this->view->paging = $this->helper->util()->paging($quantitative_total_record, $this->request->getQuery(), $limit_of_page, $current_page);

    }

    public function createQuantitativeAction()
    {
        $this->view->activemenu = [
            'recipe',
            'quantitative_create'
        ];
        $this->view->names = [
            [
                'label' => 'Tạo định lượng',
                'href' => '/admin/quantitative/createQuantitative'
            ],
        ];
        $quantitative = new Quantitative();
        $form = new QuantitativeForm();
        $form->create();
        $this->view->form = $form;
        if ($this->request->isPost()) {
            $post = $this->request->getPost();
            $quantitative->setId($quantitative->getSequenceId());
            $form->bind($post, $quantitative);
            $error = Quantitative::checkValidations($post);
            if (count($error) != 0) {
                foreach ($error as $er) {
                    $this->flashSession->error($this->helper->translate($er));
                }
            } else {
                if ($quantitative->save()) {
                    $this->flashSession->success($this->helper->translate('Tạo định lượng thành công'));
                    return $this->redirect('/admin/quantitative/listQuantitative');
                } else {
                    foreach ($quantitative->getMessages() as $message) {
                        $this->flashSession->error($this->helper->translate($message->getMessage()));
                    }
                    $form->setEntity($post);
                }
            }
        }
    }

    public function deleteQuantitativeAction($id)
    {
        $this->view->disable();
        $status_id_disable = Status::getStatusIdByCode('disable');
        $quantitative = Quantitative::findFirst([
            'conditions' => 'id=:id:',
            'bind' => [
                'id' => $id
            ]
        ]);
        if ($quantitative) {
            $quantitative->setStatusId($status_id_disable);
            $this->flashSession->success($this->helper->translate('Xóa thành công'));
            $quantitative->save();
        } else {
            $this->flashSession->warning($this->helper->translate('Không tìm thấy định lượng'));

        }
        return $this->redirect('/admin/quantitative/listQuantitative');
    }

    public function editQuantitativeAction($id)
    {
        $this->view->activemenu = [
            'recipe',
            'quantitative_list'
        ];
        $this->view->names = [
            [
                'label' => 'Chỉnh sửa định lượng',
                'href' => '/admin/quantitative/listQuantitative'
            ],
        ];
        $form = new QuantitativeForm();
        $form->edit();

        $quantitative = Quantitative::findFirst([
            'conditions' => 'id=:id:',
            'bind' => [
                'id' => $id
            ]
        ]);
        if ($this->request->isPost()) {
            $post = $this->request->getPost();
            if($post['name'] != $quantitative->getName())
            {
                $check=Quantitative::findFirst([
                    'conditions'=>'name=:name:',
                    'bind'=>[
                        'name'=>$post['name']
                    ]
                ]);
                if($check)
                {
                    $this->flashSession->error('Tên định lượng đã tồn tại');
                    return $this->redirect('/admin/quantitative/listQuantitative');
                }
            }
            if($post['code'] != $quantitative->getCode())
            {
                $check=Quantitative::findFirst([
                    'conditions'=>'code=:code:',
                    'bind'=>[
                        'code'=>$post['code']
                    ]
                ]);
                if($check)
                {
                    $this->flashSession->error('Mã số định luọng đã tồn tại');
                    return $this->redirect('/admin/quantitative/listQuantitative');
                }
            }
            if($post['short_code'] != $quantitative->getShortCode())
            {
                $check=Quantitative::findFirst([
                    'conditions'=>'short_code=:short_code:',
                    'bind'=>[
                        'short_code'=>$post['short_code']
                    ]
                ]);
                if($check)
                {
                    $this->flashSession->error('Mã số rút gọn định lượng đã tồn tại');
                    return $this->redirect('/admin/quantitative/listQuantitative');
                }
            }
            $form->bind($post, $quantitative);
            if ($quantitative->save()) {
                $this->flashSession->success($this->helper->translate('Chỉnh sửa định lượng thành công'));
                return $this->redirect('/admin/quantitative/listQuantitative');
            } else {
                foreach ($quantitative->getMessages() as $message) {
                    $this->flashSession->error($this->helper->tranlate($message->getMessage()));
                }
            }
        } else {
            $form->setEntity($quantitative);
        }

        $this->view->form = $form;
    }

    public function viewRawMaterialAction($id)
    {
        $this->view->activemenu = [
            'recipe',
            'raw_material_list'
        ];
        $this->view->names = [
            [
                'label' => 'Xem thông tin nguyên liệu',
                'href' => '/admin/raw-material/listRawMaterial'
            ],
        ];
        $form = new RawMaterialForm();
        $form->view();
        $raw_material = RawMaterial::findFirst([
            'conditions' => 'id=:id:',
            'bind' => [
                'id' => $id
            ]
        ]);
        $form->setEntity($raw_material);
        $this->view->form = $form;
    }
}